# Generated by Django 5.0.2 on 2024-04-29 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default='', max_length=100)),
                ('cardName', models.CharField(default='', max_length=100)),
                ('uri', models.CharField(default='', max_length=256)),
                ('cmc', models.IntegerField(default=0)),
                ('oracle_text', models.CharField(default='', max_length=256)),
                ('img_small', models.CharField(default='', max_length=256)),
                ('img_png', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LastCardIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_index', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PageNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deckName', models.CharField(default='', max_length=50)),
                ('cards', models.ManyToManyField(to='core.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
