# Generated by Django 5.0.2 on 2024-03-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=1)),
            ],
        ),
    ]
