# Generated by Django 5.0.2 on 2024-05-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_collection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=20),
        ),
    ]
