# Generated by Django 5.0.2 on 2024-03-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lastcardindex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastCardIndex',
        ),
    ]
