# Generated by Django 5.0.2 on 2024-05-10 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_deck_visibility_deck_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
