# Generated by Django 5.0.2 on 2024-05-10 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_deck_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='wins',
        ),
    ]
