# Generated by Django 5.0.2 on 2024-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_card_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deckName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
