# Generated by Django 5.0.2 on 2024-04-05 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_deck_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassUser',
        ),
    ]
