# Generated by Django 5.0.2 on 2024-04-05 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_card_id_card_cardname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cardName',
            new_name='card_id',
        ),
    ]
